---

galaxy_info:
  author: spamcomm
  description: Best practices structure for an Ansible playbook
  company: spamcomm
  version: 1.0.0
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: EL
    versions:
    - all
    - 5
    - 6
    - 7
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
    - development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
  dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
